---
name: tox

on:
  merge_group:
    branches:
      - "main"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_call:
concurrency:
  # Avoids canceling push to main of the same commit (github.sha) but will
  # cancel running builds when you update the source branch of a PR.
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  checks: read
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  tox:
    uses: ansible/team-devtools/.github/workflows/tox.yml@main
    secrets: inherit
    with:
      min_python: "3.12"
      default_python: "3.12"
      max_python: "3.14"
      other_names: |
        lint
        hooks
        image
      platforms: linux,macos
